### PR TITLE
Add interface to `nwm_client_new` for Azure Blob Storage

### PR DESCRIPTION
**Pull request by jarq6c**
Adds a concrete interface for accessing NWM files on Azure Blob Storage.

## Additions

`AzureFileCatalog` class for discovering files on Azure Blob Storage. Inherits from `NWMFileCatalog`.

## Removals

- None

## Changes

- Added example to `README.md`.

## Testing

1. Added basic tests commensurate with other concrete implementations of `NWMFileCatalog`.

## Notes

- None

## Todos

- None

## Checklist

- [x] PR has an informative and human-readable title
- [x] PR is well outlined and documented. See [#12](https://github.com/jarq6c/evaluation_tools/pull/12) for an example
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (see [CONTRIBUTING.md](../CONTRIBUTING.md))
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output) using [numpy docstring](https://numpydoc.readthedocs.io/en/latest/format.html) formatting
- [ ] Placeholder code is flagged / future todos are captured in comments
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by jarq6c** [comment]
Closes #235

**Review by christophertubbs — APPROVED** [review]
My only 'complaint' is the name of the package `nwm_client_new`, but that's out of scope for this. Everything is well documented and the code is easy to read. If I were to be ruthless, I'd say that line 80 in `AzureFileCatalog.py` might read better as:

```python
    return [
        os.path.join(self.server, url)
        for url in list(blobs)
        if must_contain in url
    ]
```

instead of

```python
    return [self.server+b for b in list(blobs) if must_contain in b]
```

That's only if I try my hardest to be picky.

A+

**Comment by jarq6c** [comment]
Thanks @christophertubbs !

**Comment by jarq6c** [comment]
Passes all tests. Heeded advice for more explicit URL handling, but used our own handling from `_restclient`.

**Comment by jarq6c** [comment]
Deployed: https://pypi.org/project/hydrotools.nwm-client-new/7.3.0/

**Pull request merged**
