### PR TITLE
Make map conversions more efficient alternative

### PR DESCRIPTION
**Pull request by jarq6c**
This is an alternative to #188 . This PR removes the conversion step when checking contingency tables, resulting in much faster computations for categorical metrics.

## Additions

- None

## Removals

- `convert_mapping_values`

## Changes

- contingency tables are converted directly to `pandas.Series` of the appropriate type.

## Testing

1. Removed test for `convert_mapping_values`

## Notes

-

## Todos

-

## Checklist

- [x] PR has an informative and human-readable title
- [x] PR is well outlined and documented. See [#12](https://github.com/jarq6c/evaluation_tools/pull/12) for an example
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (see [CONTRIBUTING.md](../CONTRIBUTING.md))
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output) using [numpy docstring](https://numpydoc.readthedocs.io/en/latest/format.html) formatting
- [ ] Placeholder code is flagged / future todos are captured in comments
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by jarq6c** [comment]
@groutr hopefully you don't mind reviewing this PR? :)

**Comment by jarq6c** [comment]
@aaraney any comments on this?

**Comment by aaraney** [comment]
> @aaraney any comments on this?

Looks good! Thanks for tagging me!

**Comment by jarq6c** [comment]
These tests passed locally and also passed on GH prior to pip version 22.1. The tests on `main` will pass once #169 is merged in.

**Pull request merged**
