### PR TITLE
MAJOR CHANGE: Rebranding package namespace from evaluation_tools to HydroTools (hydrotools)

### PR DESCRIPTION
**Pull request by aaraney**
The decision has been made to change the projects name from `evaluation_tools` to `HydroTools`. We feel this name better represents/describes the goals of the project and as such, the repo remote name has also been changed prior to this PR.

The bulk of this PR moves both source and test file references and documentation under the new namespace and branding.

## Changes

- python package namespace from `evaluation_tools` to `hydrotools`in source and test files
- branding of package now camel cased as `HydroTools`
- developer installation procedure changed from `pip install -e .` to `python setup.py develop`. The former will no longer work.
- all major package versions bumped:
  - `hydrotools`: 2.0.0-alpha.0
  - `hydrotools.metrics`: 1.0.0-alpha.0
  - `hydrotools.events`: 1.0.0-alpha.0
  - `hydrotools.gcp_client`: 1.0.0-alpha.0
  - `hydrotools.nwis_client`: 2.0.0-alpha.0
  - `hydrotools._restclient`: 2.0.0-alpha.0

## Notes

-

## Todos

- fix href to `hydrotools._restclient` made in 9779ab2 prior to deploy

## Checklist

- [x] PR has an informative and human-readable title
- [x] PR is well outlined and documented. See [#12](https://github.com/jarq6c/evaluation_tools/pull/12) for an example
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (see [CONTRIBUTING.md](../CONTRIBUTING.md))
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output) using [numpy docstring](https://numpydoc.readthedocs.io/en/latest/format.html) formatting
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by jarq6c** [comment]
1. Yeah, so far the major limitation seems to be the top level package installation
2. I can install each subpackage separately, use them, and successfully run pytest
3. Can you confirm that package names with a `.` are compatible with PyPI? I was expecting something like
```SUBPACKAGE_SLUG = f"{NAMESPACE_PACKAGE_NAME}-{SUBPACKAGE_NAME}"```

There's a few superficial tweeks we can make here and there, but it appears functional so far.

**Comment by aaraney** [comment]
>     1. Yeah, so far the major limitation seems to be the top level package installation

Right, with this implementation we are making the assumption that a user will not install the package from a bdist wheel. That does not mean that you can't do that, but it will pull the subpackages from github. The only way to install the package from source is by using `python setup.py develop`. I am not pleased with the trade off, but given the nature of python packaging and how the average user installs things, I think this okay for now. Do you disagree?

>     3. Can you confirm that package names with a `.` are compatible with PyPI? I was expecting something like
>        `SUBPACKAGE_SLUG = f"{NAMESPACE_PACKAGE_NAME}-{SUBPACKAGE_NAME}"`

I am making this assumption that anything I can install on test.pypi.org will also be acceptable on pypi.org. If that assumption holds (I have no reason to believe that wouldn't be the case) then yes, PyPi is fine with dots in the names.
Example [1](https://test.pypi.org/project/ns-pkg.sub1/) and [2](https://test.pypi.org/project/ns-pkg.sub2/)

Also there is this package on [pypi](https://pypi.org/project/kreagroup.jsi18n/) that has a dot in the name.


> There's a few superficial tweeks we can make here and there, but it appears functional so far.

Great! Thanks for taking a glance at this.

**Comment by jarq6c** [comment]
Ah OK I see. I had a momentary lapse of judgement. I had forgotten how we normally install the package. I was stuck in developer mode (gross!). The dot format is actually more preferable to me. I'm glad it's PyPI compatible.

**Comment by aaraney** [comment]
@hellkite500 He finally said it haha:

> I was stuck in developer mode (gross!). 

> The dot format is actually more preferable to me. I'm glad it's PyPI compatible.

Likewise. *A cohesive experience*.

Well with that, is it safe to remove the WIP tag and move forward with the merge? Or what are your thoughts?

**Comment by jarq6c** [comment]
I'm gonna say yes, buy I'm feeling particularly band-aid rippery today. So
use your best judgement.

**Comment by aaraney** [comment]
😂

**Comment by hellkite500** [comment]
Haha! We are always stuck in developer mode! Also before you merge [check this](https://isitreadonlyfriday.com/)

**Comment by aaraney** [comment]
> Haha! We are always stuck in developer mode! Also before you merge [check this](https://isitreadonlyfriday.com/)

😂 I was expecting to be Rick Rolled, but that's a new one hahah.

**Comment by aaraney** [comment]
Just for the context of this PR, I am going to rebase onto master without moving the package or subpackage versions to something non-`alpha`. After guaranteeing that everything is stable on main, I will remove the `alpha` tags.

**Pull request merged**
